name: Rust CI
on:
  workflow_call:
    inputs:
      cargo-color:
        description: 'should cargo use colors? (always, never, auto) https://doc.rust-lang.org/cargo/reference/config.html#termcolor'
        default: always
        type: string
jobs:
  build_and_test:
    env:
      CARGO_TERM_COLOR: ${{ inputs.cargo-color}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
