name: Format & Clippy & Build & Test
on:
  workflow_call:
    inputs:
      cargo-color:
        description: 'should cargo use colors? (always, never, auto) https://doc.rust-lang.org/cargo/reference/config.html#termcolor'
        default: always
        type: string
env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: ${{ inputs.cargo-color}}
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update nightly && rustup default nightly && rustup component add rustfmt 
      - run: cargo +nightly fmt --check
  clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add clippy 
      - run: cargo +${{ matrix.toolchain }} clippy --all-targets --all-features
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo +${{ matrix.toolchain }} build --verbose
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo +${{ matrix.toolchain }} test --verbose
