name: Publish Crate
on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      cargo-color:
        description: 'should cargo use colors? (always, never, auto) https://doc.rust-lang.org/cargo/reference/config.html#termcolor'
        default: always
        type: string
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: true
jobs:
  publish-crate:
    env:
      CARGO_TERM_COLOR: ${{ inputs.cargo-color}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: 'cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --package ${{ inputs.package-name }}'
